# docker/override.voice.yml
# Keep STT/TTS on the robot-net only; do not forward STT from voice_gateway here.
# When you add voice_gateway, ensure it DOES NOT forward 10300 (per 2025-09-24 note).

services:
  wyoming-piper:
    environment:
      - TZ=${TZ:-America/Los_Angeles}
  wyoming-whisper:
    environment:
      - TZ=${TZ:-America/Los_Angeles}
