version: "3.9"
services:
  dashboard:
    image: nginx:alpine
    container_name: robot-dashboard
    ports:
      - "${DASHBOARD_PORT:-8081}:80"
    volumes:
      - ../site:/usr/share/nginx/html:ro
    restart: unless-stopped
